version: '3'

services:
  crypto-3:
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M
    container_name: crypto-3
    # This should be the directory your dockerfile exists in.
    # Note, other challenges will live in ./ too, so ensure your directory name is adequately unique (comapnyname-challengename)
    build: ./lkw-padding
    # Ports! the syntax is <external>:<containerlocal>
    # Ensure the external port is within the correct range. You can use whatever local port you wish (as long as it doesn't break anything)
    ports:
        - 3300:1337

